# Hugo configuration
# update baseURL with your GitHub Pages URL

baseURL = "https://graemenewlands.com/"
languageCode = "en-us"
title = "Graeme Newlands"
theme = "ananke"

[params]
  featured_image = "/images/cover.jpeg"
  mainSections = ["posts"]
  [params.ananke]
    show_recent_posts = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "ops5-apps"
    name = "OPS5 Apps"
    url = "#"
    weight = 2
  [[menu.main]]
    parent = "ops5-apps"
    identifier = "cassandra"
    name = "Cassandra Simulator"
    url = "/cassandra/"
    weight = 1
  [[menu.main]]
    parent = "ops5-apps"
    identifier = "life"
    name = "Game of Life"
    url = "/life/"
    weight = 2
  [[menu.main]]
    parent = "ops5-apps"
    identifier = "schema"
    name = "Schema Synthesizer"
    url = "/schema/"
    weight = 3


