# Hugo configuration
# update baseURL with your GitHub Pages URL

baseURL = "https://graemenewlands.com/"
languageCode = "en-us"
title = "Graeme Newlands"
theme = "ananke"

[params]
  featured_image = "/images/cover.jpeg"
  mainSections = ["posts"]
  [params.ananke]
    show_recent_posts = true

